import "@/assets/style/global.scss";
import Loading from "@/components/Loading";
import { config } from "@fortawesome/fontawesome-svg-core";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Providers } from "./providers";
config.autoAddCss = false;

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Money Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/image/favicon.ico" />
      </head>
      <body className={`${nunito.className} antialiased relative`}>
        <Providers>
          <Loading />
          {children}
        </Providers>
      </body>
    </html>
  );
}
